version: '2'
services:
  zookeeper:
    image: wurstmeister/kafka
    container_name: zookeeper
    ports:
      - 22181:2181
  
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT=zookeeper: zookeeper:2181